#!/usr/bin/env python3
"""
PRD M4 — the bridge: the ONLY interface between loop-backend and the
human-built frontend (globe/food3d.html). Serves Mongo-backed JSON over a
tiny local HTTP service AND writes static bridge/out/*.json for a fully
offline console (pull-the-cable demo). The loop NEVER edits globe/*.html.

Endpoints (see bridge/CONTRACT.md for the full shapes + provenance):
  GET /operator_sites            -> operator portfolio as GeoJSON (modeled-portfolio)
  GET /response?recall=<id>      -> the live M2 Response (exposure/risk/action)
  GET /transcript?recall=<id>    -> the M3 swarm tool-call log
  GET /telemetry                 -> GB10 telemetry (stub off-box; real NVML on-box M6)
  GET /healthz                   -> liveness

Static offline mirror (bridge/out/): operator_sites.json, response.json,
transcript.json, telemetry.json — generated by `server.py --write-out` and
committed so the console renders with the network unplugged.

Provenance: every payload carries `provenance` splitting `real` vs `modeled`
fields (instrument, not oracle). The frontend must surface that distinction.
"""
import argparse
import json
import os
import sys
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, ROOT)

from db.queries import get_db  # noqa: E402
from sim.respond import respond  # noqa: E402
import agent.swarm as swarm  # noqa: E402

PORT = int(os.environ.get("BREADCRUMBS_PORT", "8899"))
OUT_DIR = os.path.join(os.path.dirname(__file__), "out")
SAMPLES_DIR = os.path.join(os.path.dirname(__file__), "samples")
DEFAULT_RECALL = "F-0757-2022"  # the Dole hero recall


# ── payload builders (shared by HTTP + static-out so the shapes match) ────────
def operator_sites_geojson(db=None):
    """The operator portfolio as a GeoJSON FeatureCollection. Each site is a
    real DOHMH establishment; its supplier link is MODELED (labeled)."""
    db = get_db() if db is None else db
    features = []
    for s in db.operator_sites.find({}):
        loc = s.get("loc") or {"type": "Point", "coordinates": [0, 0]}
        features.append({
            "type": "Feature",
            "geometry": loc,
            "properties": {
                "camis": s.get("camis"),
                "name": s.get("name"),
                "boro": s.get("boro"),
                "cuisine": s.get("cuisine"),
                "grade": s.get("grade"),
                "crit_violations": int(s.get("crit_violations", 0)),
                "distributor": s.get("distributor"),
                "distributor_rule": s.get("distributor_rule"),
                "primary_hub": s.get("primary_hub"),
                "hub_distance_m": s.get("hub_distance_m"),
                "provenance": {
                    "source": s.get("provenance", {}).get("source"),
                    "fetched_at": s.get("provenance", {}).get("fetched_at"),
                    "class": s.get("provenance", {}).get("class", "modeled-portfolio"),
                },
            },
        })
    return {
        "type": "FeatureCollection",
        "features": features,
        "count": len(features),
        "provenance": {
            "class": "modeled-portfolio",
            "note": "real DOHMH establishments; supplier->site links are MODELED (FSMA-204 gap)",
        },
    }


def response_payload(recall_number, db=None):
    """The live M2 Response for a recall. Numbers come straight from
    sim.respond.respond() — the bridge never recomputes, so there is no drift."""
    db = get_db() if db is None else db
    recall = db.recalls.find_one({"recall_number": recall_number})
    if recall is None:
        recall = db.recalls.find_one({"recalling_firm": recall_number})
    if recall is None:
        return {"error": "recall not found: %s" % recall_number, "recall_number": recall_number}
    recall["_id"] = str(recall["_id"])
    resp = respond(recall, db)
    return _jsonable(resp)


def transcript_payload(recall_number, db=None, adapter=None):
    """The M3 swarm tool-call transcript for a recall. Runs the swarm (which
    persists to agent_memory + dedupes) and returns the ordered tool-call log.
    The canonical subsequence is preserved (see CONTRACT.md)."""
    db = get_db() if db is None else db
    adapter = adapter if adapter is not None else swarm.ModelAdapter(backend="openrouter")
    out = swarm.run(recall_number, db=db, adapter=adapter)
    return {
        "recall_number": recall_number,
        "deduped": out.get("deduped"),
        "alert_count": out.get("alert_count"),
        "canonical_order": ["watch_feed", "ingest_recall", "trace_forward",
                            "score_risk", "brief", "draft_sms"],
        "entries": _jsonable(out.get("transcript", [])),
        "provenance": {"class": "real", "source": "agent.swarm transcript log"},
    }


def telemetry_payload():
    """GB10 telemetry. Stub off-box (M6 wires real NVML/tegrastats).
    nvidia-smi under-reports on GB10 unified memory — M6 reads tegrastats."""
    return {
        "model": "openrouter/glm (off-box stub; on-box swap -> Nemotron/NemoClaw)",
        "tokens_per_sec": None,
        "unified_gb": None,
        "unified_gb_total": 128,
        "watts": None,
        "agents_concurrent": 0,
        "source": "stub",
        "note": "off-box dev stub; M6 wires real NVML/tegrastats on the GB10",
        "ts": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }


def _jsonable(x):
    try:
        json.dumps(x, default=str)
        return x
    except (TypeError, ValueError):
        return str(x)


# ── static offline mirror: bridge/out/*.json ─────────────────────────────────
def write_out(recall_number=DEFAULT_RECALL, db=None):
    """Generate bridge/out/*.json so the console renders fully offline.
    Also writes the canned samples to bridge/samples/ (committed, stable)."""
    db = get_db() if db is None else db
    os.makedirs(OUT_DIR, exist_ok=True)
    os.makedirs(SAMPLES_DIR, exist_ok=True)

    # rebuild a clean swarm run for the sample transcript (force_alert so the
    # sample reflects a real first-alert, not a deduped re-run)
    db.agent_memory.delete_many({"recall_id": recall_number})
    adapter = swarm.ModelAdapter(backend="openrouter")
    out = swarm.run(recall_number, db=db, adapter=adapter, force_alert=True)

    payloads = {
        "operator_sites.json": operator_sites_geojson(db),
        "response.json": response_payload(recall_number, db),
        "transcript.json": {
            "recall_number": recall_number,
            "deduped": out.get("deduped"),
            "alert_count": out.get("alert_count"),
            "canonical_order": ["watch_feed", "ingest_recall", "trace_forward",
                                "score_risk", "brief", "draft_sms"],
            "entries": _jsonable(out.get("transcript", [])),
            "provenance": {"class": "real", "source": "agent.swarm transcript log"},
        },
        "telemetry.json": telemetry_payload(),
        "brief.json": _jsonable(out.get("brief")),
        "sms.json": _jsonable(out.get("sms")),
    }
    for name, payload in payloads.items():
        path = os.path.join(OUT_DIR, name)
        with open(path, "w") as f:
            json.dump(payload, f, indent=2, default=str, sort_keys=True)
        print("[bridge/out] wrote %s (%d bytes)" % (name, os.path.getsize(path)))
        # mirror the stable sample payloads (committed; the console fetches these
        # offline before the live bridge exists)
        if name in ("operator_sites.json", "response.json", "transcript.json",
                    "telemetry.json"):
            spath = os.path.join(SAMPLES_DIR, name)
            with open(spath, "w") as f:
                json.dump(payload, f, indent=2, default=str, sort_keys=True)
            print("[bridge/samples] wrote %s" % name)


# ── HTTP service ──────────────────────────────────────────────────────────────
class Handler(BaseHTTPRequestHandler):
    def _send(self, code, payload):
        body = json.dumps(payload, indent=2, default=str).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")  # console is local file
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _param(self, key, default=None):
        from urllib.parse import urlparse, parse_qs
        q = parse_qs(urlparse(self.path).query)
        vals = q.get(key)
        return vals[0] if vals else default

    def do_GET(self):
        from urllib.parse import urlparse
        path = urlparse(self.path).path
        try:
            if path == "/healthz":
                self._send(200, {"ok": True, "service": "breadcrumbs-bridge"})
            elif path == "/operator_sites":
                self._send(200, operator_sites_geojson())
            elif path == "/response":
                rn = self._param("recall", DEFAULT_RECALL)
                self._send(200, response_payload(rn))
            elif path == "/transcript":
                rn = self._param("recall", DEFAULT_RECALL)
                self._send(200, transcript_payload(rn))
            elif path == "/telemetry":
                self._send(200, telemetry_payload())
            else:
                self._send(404, {"error": "unknown endpoint: %s" % path,
                                 "endpoints": ["/operator_sites", "/response?recall=<id>",
                                               "/transcript?recall=<id>", "/telemetry",
                                               "/healthz"]})
        except Exception as e:
            self._send(500, {"error": str(e), "type": type(e).__name__})

    def log_message(self, fmt, *args):
        sys.stderr.write("[bridge] %s - %s\n" % (self.address_string(), fmt % args))


def serve(port=PORT):
    httpd = ThreadingHTTPServer(("127.0.0.1", port), Handler)
    print("[bridge] serving on http://127.0.0.1:%d (endpoints: /operator_sites "
          "/response /transcript /telemetry /healthz)" % port)
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\n[bridge] stopped")
    finally:
        httpd.server_close()


if __name__ == "__main__":
    a = argparse.ArgumentParser(description="BREADCRUMBS bridge — backend -> frontend")
    a.add_argument("--port", type=int, default=PORT)
    a.add_argument("--write-out", action="store_true",
                   help="generate bridge/out/*.json + bridge/samples/*.json and exit")
    a.add_argument("--recall", default=DEFAULT_RECALL,
                   help="recall_number for the static sample (default: Dole F-0757-2022)")
    args = a.parse_args()
    if args.write_out:
        write_out(recall_number=args.recall)
    else:
        serve(args.port)
